### ISSUE TITLE
Use a gresource for icons and stylesheet

### ISSUE THREAD

**Issue by danirabbit** [lozanotux/Dribbble#2]
You should use a GResource to compile your assets into your app. 

You can see [an example gresource.xml file here](https://github.com/elementary/mail/blob/rewrite/data/io.elementary.mail.gresource.xml)

[An example of how to compile the resource here](https://github.com/elementary/photos/blob/master/src/CMakeLists.txt#L230)

And then of course you can [load css from a resource](https://github.com/elementary/mail/blob/rewrite/src/Application.vala#L78)

**Comment by lozanotux** [comment]
Done!
